# Generated by Django 5.0.2 on 2024-03-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_managers_alter_address_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
