# Generated by Django 5.0.2 on 2024-03-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name_plural': 'MainCategories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'SubCategories'},
        ),
    ]
