# Generated by Django 5.0.2 on 2024-05-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_category_options_alter_maincategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='phone',
        ),
    ]
