# Generated by Django 5.0.2 on 2024-05-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
