# Generated by Django 5.0.2 on 2024-05-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_delete_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_img',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
