# Generated by Django 5.0.2 on 2024-05-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_remove_product_availability_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
